# This is a basic workflow to help you get started with Actions

name: auto_report_cron_job

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '0 9,21 * * *'
  workflow_dispatch:

jobs:
  run-and-commit:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - run: python -m pip install -r requirements.txt
      - run: python main.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: Karim Habouch
          author_email: karim.habush@gmail.com
          message: 'Automatic update with GitHub Actions'
          add: 'README.md'

